version: '3.8'
services:

  payment_api:
    extends:
      file: docker-compose.yaml
      service: payment_api
    ports:
      - "8000:8000"
    env_file:
      - dev.env

  subscription_api:
    extends:
      file: docker-compose.yaml
      service: subscription_api
    ports:
      - "8001:8001"
    env_file:
      - dev.env

  admin:
    extends:
      service: admin
      file: docker-compose.yaml
    ports:
      - "8002:8002"
    env_file:
      - dev.env

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - "5432:5432"
    env_file:
      - dev.env

  redis:
    extends:
      file: docker-compose.yaml
      service: redis

  rabbit:
    extends:
      file: docker-compose.yaml
      service: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  order_scheduler:
    extends:
      file: docker-compose.yaml
      service: order_scheduler

  order_worker:
    extends:
      file: docker-compose.yaml
      service: order_worker

  payment_scheduler:
    extends:
      file: docker-compose.yaml
      service: payment_scheduler
    env_file:
      - dev.env

  payment_worker:
    extends:
      file: docker-compose.yaml
      service: payment_worker
    env_file:
      - dev.env

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  postgresdata:
  redis-data: